name: delivery_app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  path: ^1.9.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  provider: ^6.1.2
  flutter_stripe: ^11.1.0
  http: ^1.2.2
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0
  firebase_messaging: ^15.1.3
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - .env
